/**
 * Códigos de banco (`bank_code`) que acepta la API de payouts de dLocal Go por país.
 *
 * IMPORTANTE: dLocal **no** acepta el nombre del banco como texto libre; exige el
 * `bank_code` exacto de su tabla. dLocal Go **no** ofrece un endpoint para listar bancos,
 * por lo que estas tablas se transcriben de la documentación oficial de dLocal Go
 * ("Payouts Integration → Country requirements"). No mezclar con dLocal V3 (docs.dlocal.com),
 * que usa otro contrato (`beneficiary.bank_account.code`) y otros códigos.
 *
 * Fuente: https://docs.dlocalgo.com/integration-api/llms-full.txt (Country requirements).
 * Última sincronización: 2026-07 (dLocal Go).
 *
 * Para regenerar: bajar el corpus y volver a parsear las tablas "### Bank codes" por país.
 */

import type { DlocalPayoutCountry } from "./dlocalPayouts.js";

export type DlocalBankCode = {
  /** Nombre del banco tal como lo publica dLocal Go. */
  name: string;
  /** Valor exacto a enviar en `bank_code`. */
  code: string;
};

/** Argentina — dLocal Go Country requirements. */
const AR_BANK_CODES: DlocalBankCode[] = [
  { name: "Bacs Banco de Credito Y Securitizacion", code: "340" },
  { name: "Banco B. I. Creditanstalt", code: "147" },
  { name: "Banco Bica S.A.", code: "426" },
  { name: "Banco Bradesco Argentina", code: "336" },
  { name: "Banco Cetelem Argentina", code: "331" },
  { name: "Banco CMF", code: "319" },
  { name: "Banco Coinag S.A.", code: "431" },
  { name: "Banco Columbia", code: "389" },
  { name: "Banco Comafi", code: "299" },
  { name: "Banco Credicoop Coop. L", code: "191" },
  { name: "Banco de Comercio S.A.", code: "432" },
  { name: "Banco de Corrientes", code: "094" },
  { name: "Banco de Formosa", code: "315" },
  { name: "Banco de Galicia Y Buenos Aires", code: "007" },
  { name: "Banco de Inversion Y Comercio Exterior", code: "300" },
  { name: "Banco de La Ciudad de Buenos Aires", code: "029" },
  { name: "Banco de La Nacion Argentina", code: "011" },
  { name: "Banco de La Pampa Sociedad de Economia M", code: "093" },
  { name: "Banco de La Provincia de Buenos Aires", code: "014" },
  { name: "Banco de La Provincia de Cordoba", code: "020" },
  { name: "Banco de La Republica Oriental Del Uruguay", code: "269" },
  { name: "Banco de San Juan", code: "045" },
  { name: "Banco de Santa Cruz", code: "086" },
  { name: "Banco de Santiago del Estero", code: "321" },
  { name: "Banco de Servicios Financieros", code: "332" },
  { name: "Banco de Servicios Y Transacciones", code: "338" },
  { name: "Banco de Valores", code: "198" },
  { name: "Banco Del Chubut", code: "083" },
  { name: "Banco Del Sol", code: "310" },
  { name: "Banco Dino S.A.", code: "448" },
  { name: "Banco Hipotecario", code: "044" },
  { name: "Banco Julio", code: "305" },
  { name: "Banco Macro", code: "285" },
  { name: "Banco Mariva", code: "254" },
  { name: "Banco Mas Ventas", code: "341" },
  { name: "Banco Meridian", code: "281" },
  { name: "Banco Municipal de Rosario", code: "065" },
  { name: "Banco Patagonia Sudameris", code: "034" },
  { name: "Banco Piano", code: "301" },
  { name: "Banco Provincia de Tierra Del Fuego", code: "268" },
  { name: "Banco Provincia Del Neuquen", code: "097" },
  { name: "Banco Roela", code: "247" },
  { name: "Banco Saenz", code: "277" },
  { name: "Banco Santander", code: "072" },
  { name: "Banco Sucredito Regional S.A.U.", code: "435" },
  { name: "Banco Supervielle S.A.", code: "027" },
  { name: "Banco Voii S.A.", code: "312" },
  { name: "Bank of America, National Associa", code: "262" },
  { name: "Bank of Chine Limited Sucursal Buenos Aires", code: "515" },
  { name: "BBVA", code: "017" },
  { name: "Bnp Paribas", code: "266" },
  { name: "Brubank S.A.U.", code: "143" },
  { name: "CVU Account", code: "000" },
  { name: "Citibank", code: "016" },
  { name: "HSBC Bank Argentina", code: "150" },
  { name: "Industrial and Commercial Bank of China (ICBC) Argentina", code: "015" },
  { name: "J P Morgan Chase Bank Sucursal Buenos Aires", code: "165" },
  { name: "Lloyds Tsb Bank", code: "010" },
  { name: "NARANJA DIGITAL COMPAÑÍA FINANCIERA S.A.", code: "453" },
  { name: "Nuevo Banco de Entre Rios", code: "386" },
  { name: "Nuevo Banco de La Rioja", code: "309" },
  { name: "Nuevo Banco de Santa Fe", code: "330" },
  { name: "Nuevo Banco Del Chaco", code: "311" },
  { name: "Nuevo Banco Industrial de Azul", code: "322" },
  { name: "RCI Banque Argentina", code: "339" },
  { name: "Wilobank S.A.", code: "384" }
];

/** Brasil — dLocal Go Country requirements. */
const BR_BANK_CODES: DlocalBankCode[] = [
  { name: "Acesso Soluções Pagamento S.A.", code: "332" },
  { name: "Banco A.J. Renner S.A.", code: "654" },
  { name: "Banco ABC Brasil S.A.", code: "246" },
  { name: "Banco ABN Amro S.A.", code: "075" },
  { name: "Banco Agiplan S.A.", code: "121" },
  { name: "Banco Alfa S.A.", code: "025" },
  { name: "Banco AndBank (Brasil) S.A.", code: "065" },
  { name: "Banco Arbi S.A.", code: "213" },
  { name: "Banco B3 S.A.", code: "096" },
  { name: "Banco Bandepe S.A.", code: "024" },
  { name: "Banco Bari de Investimentos e Financiamentos S.A.", code: "330" },
  { name: "Banco BMG S.A.", code: "318" },
  { name: "Banco BNP Paribas Brasil S.A.", code: "752" },
  { name: "Banco Bocom BBM S.A.", code: "107" },
  { name: "Banco Bonsucesso S.A.", code: "218" },
  { name: "Banco Bradescard S.A.", code: "063" },
  { name: "Banco Bradesco BBI S.A.", code: "036" },
  { name: "Banco Bradesco BERJ S.A.", code: "122" },
  { name: "Banco Bradesco Financiamentos S.A.", code: "394" },
  { name: "Banco Bradesco S.A.", code: "237" },
  { name: "Banco BTG Pactual S.A.", code: "208" },
  { name: "Banco C6 S.A.", code: "336" },
  { name: "Banco Caixa Geral - Brasil S.A.", code: "473" },
  { name: "Banco Capital S.A.", code: "412" },
  { name: "Banco Cargill S.A.", code: "040" },
  { name: "Banco Cédula S.A.", code: "266" },
  { name: "Banco Cetelem S.A.", code: "739" },
  { name: "Banco Cifra S.A.", code: "233" },
  { name: "Banco Citibank", code: "745" },
  { name: "Banco Clássico S.A.", code: "241" },
  { name: "Banco Cooperativo do Brasil S.A. - Bancoob", code: "756" },
  { name: "Banco Cooperativo Sicredi S.A.", code: "748" },
  { name: "Banco Crédit Agricole Brasil S.A.", code: "222" },
  { name: "Banco Credit Suisse (Brasil) S.A.", code: "505" },
  { name: "Banco Crefisa S.A.", code: "069" },
  { name: "Banco da Amazônia S.A.", code: "003" },
  { name: "Banco da China Brasil S.A.", code: "083" },
  { name: "Banco Daycoval S.A.", code: "707" },
  { name: "Banco de Brasília S.A. - BRB", code: "070" },
  { name: "Banco de la Nación Argentina", code: "300" },
  { name: "Banco Digio S.A.", code: "335" },
  { name: "Banco do Brasil S.A.", code: "001" },
  { name: "Banco do Estado de Sergipe S.A. - Banese", code: "047" },
  { name: "Banco do Estado do Pará S.A. - Banpará", code: "037" },
  { name: "Banco do Estado do Rio Grande do Sul S.A. - Banrisul", code: "041" },
  { name: "Banco do Nordeste do Brasil S.A.", code: "004" },
  { name: "Banco Fator S.A.", code: "265" },
  { name: "Banco Fibra S.A.", code: "224" },
  { name: "Banco Ficsa S.A.", code: "626" },
  { name: "Banco Finaxis S.A.", code: "094" },
  { name: "Banco Genial", code: "278" },
  { name: "Banco Guanabara S.A.", code: "612" },
  { name: "Banco Inbursa S.A.", code: "012" },
  { name: "Banco Industrial do Brasil S.A.", code: "604" },
  { name: "Banco Indusval S.A.", code: "653" },
  { name: "Banco Inter", code: "077" },
  { name: "Banco Investcred Unibanco S.A.", code: "249" },
  { name: "Banco Itaú BBA S.A.", code: "184" },
  { name: "Banco Itaú Consignado S.A.", code: "029" },
  { name: "Banco ItauBank S.A.", code: "479" },
  { name: "Banco J. Safra S.A.", code: "074" },
  { name: "Banco J.P. Morgan S.A.", code: "376" },
  { name: "Banco John Deere S.A.", code: "217" },
  { name: "Banco KDB do Brasil S.A.", code: "076" },
  { name: "Banco KEB Hana do Brasil S.A.", code: "757" },
  { name: "Banco Luso Brasileiro S.A.", code: "600" },
  { name: "Banco Máxima S.A.", code: "243" },
  { name: "Banco Mercantil do Brasil S.A.", code: "389" },
  { name: "Banco Mizuho do Brasil S.A.", code: "370" },
  { name: "Banco Modal S.A.", code: "746" },
  { name: "Banco Morgan Stanley S.A.", code: "066" },
  { name: "Banco MUFG Brasil S.A.", code: "456" },
  { name: "Banco Nacional de Desenvolvimento Econômico e Social", code: "007" },
  { name: "Banco Olé Bonsucesso Consignado S.A.", code: "169" },
  { name: "Banco Original", code: "212" },
  { name: "Banco Original do Agronegócio S.A.", code: "079" },
  { name: "Banco Ourinvest S.A.", code: "712" },
  { name: "Banco Panamericano S.A.", code: "623" },
  { name: "Banco Paulista S.A.", code: "611" },
  { name: "Banco Pine S.A.", code: "643" },
  { name: "Banco Rabobank International Brasil S.A.", code: "747" },
  { name: "Banco Rendimento S.A.", code: "633" },
  { name: "Banco Ribeirão Preto S.A.", code: "741" },
  { name: "Banco Rodobens S.A.", code: "120" },
  { name: "Banco Safra S.A.", code: "422" },
  { name: "Banco Santander Brasil S.A.", code: "033" },
  { name: "Banco Semear S.A.", code: "743" },
  { name: "Banco Sistema S.A.", code: "754" },
  { name: "Banco Smartbank S.A.", code: "630" },
  { name: "Banco Société Générale Brasil S.A.", code: "366" },
  { name: "Banco Sofisa", code: "637" },
  { name: "Banco Sumitomo Mitsui Brasileiro S.A.", code: "464" },
  { name: "Banco Topázio S.A.", code: "082" },
  { name: "Banco Triângulo S.A.", code: "634" },
  { name: "Banco Tricury S.A.", code: "018" },
  { name: "Banco Votorantim S.A. (Banco Neon)", code: "655" },
  { name: "Banco VR S.A.", code: "610" },
  { name: "Banco Western Union do Brasil S.A.", code: "119" },
  { name: "Banco Woori Bank do Brasil S.A.", code: "124" },
  { name: "Banco XP S.A.", code: "348" },
  { name: "BancoSeguro S.A.", code: "081" },
  { name: "Banestes S.A. Banco do Estado do Espírito Santo", code: "021" },
  { name: "Bank of America Merrill Lynch Banco Múltiplo S.A.", code: "755" },
  { name: "BCV - Banco de Crédito e Varejo S.A.", code: "250" },
  { name: "Bexs Banco de Câmbio S.A.", code: "144" },
  { name: "Bexs Corretora de Câmbio S.A.", code: "253" },
  { name: "BNY Mellon Banco S.A.", code: "017" },
  { name: "BPP Instituição de Pagamento S.A.", code: "301" },
  { name: "BR Partners Banco de Investimento S.A.", code: "126" },
  { name: "Caixa Econômica Federal - CEF", code: "104" },
  { name: "China Construction Bank (Brasil) Banco Múltiplo S.A.", code: "320" },
  { name: "Citibank N.A.", code: "477" },
  { name: "Commerzbank Brasil S.A. - Banco Múltiplo", code: "163" },
  { name: "Confederação Nacional das Cooperativas Centrais Unicreds", code: "136" },
  { name: "Cooperativa Central de Crédito Urbano - Cecred", code: "085" },
  { name: "Cora SCD S.A.", code: "403" },
  { name: "Credicoamo Crédito Rural Cooperativa", code: "010" },
  { name: "Credit Suisse Hedging-Griffo Corretora de Valores S.A.", code: "011" },
  { name: "Deutsche Bank S.A. - Banco Alemão", code: "487" },
  { name: "Goldman Sachs do Brasil Banco Múltiplo S.A.", code: "064" },
  { name: "Haitong Banco de Investimento do Brasil S.A.", code: "078" },
  { name: "Hipercard Banco Múltiplo S.A.", code: "062" },
  { name: "HSBC Brasil S.A. - Banco de Investimento", code: "269" },
  { name: "ICBC do Brasil Banco Múltiplo S.A.", code: "132" },
  { name: "ING Bank N.V.", code: "492" },
  { name: "Intesa Sanpaolo Brasil S.A. - Banco Múltiplo", code: "139" },
  { name: "Itaú Unibanco Holding S.A.", code: "652" },
  { name: "Itaú Unibanco S.A.", code: "341" },
  { name: "JPMorgan Chase Bank National Association", code: "488" },
  { name: "Kirton Bank S.A. - Banco Múltiplo", code: "399" },
  { name: "Mercadopago.com Representações Ltda.", code: "323" },
  { name: "Moneycorp Banco de Câmbio S.A.", code: "259" },
  { name: "MS Bank S.A. Banco de Câmbio", code: "128" },
  { name: "Novo Banco Continental S.A. - Banco Múltiplo", code: "753" },
  { name: "Nu Pagamentos (Nubank)", code: "260" },
  { name: "Omni Banco S.A.", code: "613" },
  { name: "PagSeguro Internet S.A.", code: "290" },
  { name: "Paraná Banco S.A.", code: "254" },
  { name: "Plural S.A. Banco Múltiplo", code: "125" },
  { name: "Scotiabank Brasil S.A. Banco Múltiplo", code: "751" },
  { name: "State Street Brasil S.A. – Banco Comercial", code: "014" },
  { name: "Stone Pagamentos S.A.", code: "197" },
  { name: "Travelex Banco de Câmbio S.A.", code: "095" },
  { name: "UBS Brasil Banco de Investimento S.A.", code: "129" },
  { name: "UBS Brasil Corretora de Câmbio Títulos e Valores Mobiliários S.A.", code: "015" },
  { name: "Unicred Norte do Paraná", code: "084" }
];

/** Ecuador — dLocal Go Country requirements. */
const EC_BANK_CODES: DlocalBankCode[] = [
  { name: "Banco Amazonas", code: "034" },
  { name: "Banco Asistencia Comunitaria Finca S.A.", code: "323" },
  { name: "Banco Bolivariano", code: "037" },
  { name: "Banco Capital S.A.", code: "061" },
  { name: "Banco Citibank", code: "024" },
  { name: "Banco Comercial de Manabi", code: "039" },
  { name: "Banco Coopnacional S.A.", code: "064" },
  { name: "Banco D-Miro S.A.", code: "063" },
  { name: "Banco de Guayaquil", code: "017" },
  { name: "Banco de Loja", code: "029" },
  { name: "Banco de Machala", code: "025" },
  { name: "Banco del Austro", code: "035" },
  { name: "Banco del Instituto Ecuatoriano de Seguridad Social", code: "461" },
  { name: "Banco del Litoral", code: "043" },
  { name: "Banco del Pacífico", code: "030" },
  { name: "Banco del Pichincha", code: "010" },
  { name: "Banco Delbank", code: "027" },
  { name: "Banco Ecuatoriano de la Vivienda", code: "052" },
  { name: "Banco Económico", code: "007" },
  { name: "Banco Ecofuturo", code: "047" },
  { name: "Banco FIE", code: "045" },
  { name: "Banco Fortaleza", code: "049" },
  { name: "Banco Ganadero", code: "009" },
  { name: "Banco General Rumiñahui", code: "042" },
  { name: "Banco Internacional", code: "032" },
  { name: "Banco Procredit", code: "060" },
  { name: "Banco Produbanco", code: "036" },
  { name: "Banco Solidario", code: "059" },
  { name: "Banecuador B.P.", code: "066" },
  { name: "Banco Desarrollo de Los Pueblos S.A.", code: "068" },
  { name: "COAC Ahorrista Solidario", code: "181" },
  { name: "COAC Sindicato de Choferes Profesionales de Yantza", code: "109" },
  { name: "Coop. 15 de Abril Ltda", code: "057" },
  { name: "Coop. 15 de Agosto Pilacoto", code: "290" },
  { name: "Coop. Accion y Desarrollo", code: "051" },
  { name: "Coop. Aho. y Cred. 16 de Junio", code: "660" },
  { name: "Coop. Aho. y Cred. 1ro de Enero del Austro", code: "284" },
  { name: "Coop. Aho. y Cred. 23 de Julio", code: "058" },
  { name: "Coop. Aho. y Cred. 23 de Mayo Ltda.", code: "606" },
  { name: "Coop. Aho. y Cred. 29 de Octubre", code: "095" },
  { name: "Coop. Aho. y Cred. 4 de Octubre Ltda.", code: "294" },
  { name: "Coop. Aho. y Cred. 9 de Octubre Ltda", code: "325" },
  { name: "Coop. Aho. y Cred. Accion Rural", code: "326" },
  { name: "Coop. Aho. y Cred. Accion Tungurahua Ltda.", code: "636" },
  { name: "Coop. Aho. y Cred. Agraria Mushuk Kawsay Ltda.", code: "275" },
  { name: "Coop. Aho. y Cred. Agricola Junin Ltda", code: "424" },
  { name: "Coop. Aho. y Cred. Alfonso Jaramillo", code: "296" },
  { name: "Coop. Aho. y Cred. Alianza del Valle Ltda", code: "062" },
  { name: "Coop. Aho. y Cred. Alianza Minas Ltda.", code: "278" },
  { name: "Coop. Aho. y Cred. Ambato Ltda", code: "414" },
  { name: "Coop. Aho. y Cred. Andina Ltda.", code: "642" },
  { name: "Coop. Aho. y Cred. Artesanos Ltda", code: "417" },
  { name: "Coop. Aho. y Cred. Atuntaqui Ltda.", code: "086" },
  { name: "Coop. Aho. y Cred. Cacpe Celica", code: "656" },
  { name: "Coop. Aho. y Cred. Cam Com Canton Bolivar", code: "426" },
  { name: "Coop. Aho. y Cred. Camara Comer Ambato", code: "411" },
  { name: "Coop. Aho. y Cred. Camara Comercio Indigena", code: "295" },
  { name: "Coop. Aho. y Cred. Cariamanga Ltda", code: "422" },
  { name: "Coop. Aho. y Cred. Carroceros de Tungurahua", code: "634" },
  { name: "Coop. Aho. y Cred. Catamayo Ltda. Mie", code: "657" },
  { name: "Coop. Aho. y Cred. Chone Ltda", code: "067" },
  { name: "Coop. Aho. y Cred. Coca Ltda", code: "607" },
  { name: "Coop. Aho. y Cred. Comercio Ltda Portoviejo", code: "088" },
  { name: "Coop. Aho. y Cred. Const Comercio y Produccion", code: "407" },
  { name: "Coop. Aho. y Cred. Cotocollao", code: "065" },
  { name: "Coop. Aho. y Cred. Credi Facil Ltda.", code: "628" },
  { name: "Coop. Aho. y Cred. Crediamigo Ltda. Loja Mi", code: "653" },
  { name: "Coop. Aho. y Cred. Cristo Rey", code: "291" },
  { name: "Coop. Aho. y Cred. de la Peq. Emp. Cacpe Macara", code: "658" },
  { name: "Coop. Aho. y Cred. de la Peq. Emp. Cacpe Zamora Ltda.", code: "602" },
  { name: "Coop. Aho. y Cred. de Los Serv. Publ. del Min. de Ed.", code: "605" },
  { name: "Coop. Aho. y Cred. Desarrollo Integral Ltda.", code: "603" },
  { name: "Coop. Aho. y Cred. Dorado Ltda", code: "415" },
  { name: "Coop. Aho. y Cred. Ecuafuturo Ltda.", code: "630" },
  { name: "Coop. Aho. y Cred. Educ del Tungurahua", code: "413" },
  { name: "Coop. Aho. y Cred. Educadores Chimborazo", code: "292" },
  { name: "Coop. Aho. y Cred. Educadores de Pastaza Ltda.", code: "204" },
  { name: "Coop. Aho. y Cred. Educadores Tulcan Ltda.", code: "085" },
  { name: "Coop. Aho. y Cred. El Calvario Ltda.", code: "627" },
  { name: "Coop. Aho. y Cred. El Sagrario", code: "069" },
  { name: "Coop. Aho. y Cred. Erco Ltda", code: "410" },
  { name: "Coop. Aho. y Cred. Esc.Sup.Politec. Agrop. de Manabi Man", code: "420" },
  { name: "Coop. Aho. y Cred. Escencia Indigena Ltda.", code: "641" },
  { name: "Coop. Aho. y Cred. Familia Austral", code: "286" },
  { name: "Coop. Aho. y Cred. Fernando Daquilema", code: "429" },
  { name: "Coop. Aho. y Cred. Fortuna Mies", code: "654" },
  { name: "Coop. Aho. y Cred. Fundesarrollo", code: "406" },
  { name: "Coop. Aho. y Cred. Futuro y Progreso de Galapagos Lt", code: "661" },
  { name: "Coop. Aho. y Cred. Gonzanama Mies", code: "650" },
  { name: "Coop. Aho. y Cred. Grameen Amazonas", code: "604" },
  { name: "Coop. Aho. y Cred. Guamote Ltda.", code: "664" },
  { name: "Coop. Aho. y Cred. Guaranda Ltda.", code: "072" },
  { name: "Coop. Aho. y Cred. Huaicana Ltda", code: "609" },
  { name: "Coop. Aho. y Cred. Huayco Pungo Ltda", code: "419" },
  { name: "Coop. Aho. y Cred. Huinara Ltda. Mies", code: "626" },
  { name: "Coop. Aho. y Cred. Inka Kipu Ltda.", code: "635" },
  { name: "Coop. Aho. y Cred. Integral", code: "409" },
  { name: "Coop. Aho. y Cred. Jadan Ltda. Mies", code: "625" },
  { name: "Coop. Aho. y Cred. Juan de Salinas Ltda.", code: "270" },
  { name: "Coop. Aho. y Cred. Juan Pio de Mora Ltda.", code: "638" },
  { name: "Coop. Aho. y Cred. La Dolorosa Ltda", code: "073" },
  { name: "Coop. Aho. y Cred. La Merced", code: "557" },
  { name: "Coop. Aho. y Cred. Llanganates", code: "348" },
  { name: "Coop. Aho. y Cred. Lucha Campesina Ltda.", code: "663" },
  { name: "Coop. Aho. y Cred. Malchingui Ltda.", code: "273" },
  { name: "Coop. Aho. y Cred. Manantial de Oro Ltda.", code: "601" },
  { name: "Coop. Aho. y Cred. Maquita Cushun Ltda.", code: "631" },
  { name: "Coop. Aho. y Cred. Marcabeli Ltda", code: "423" },
  { name: "Coop. Aho. y Cred. Mi Tierra", code: "403" },
  { name: "Coop. Aho. y Cred. Minga Ltda.", code: "293" },
  { name: "Coop. Aho. y Cred. Mujeres Unidas Tantanakushk", code: "333" },
  { name: "Coop. Aho. y Cred. Mushuc Runa Ltda", code: "412" },
  { name: "Coop. Aho. y Cred. Nuestros Abuelos Ltda", code: "416" },
  { name: "Coop. Aho. y Cred. Nueva Esperanza", code: "427" },
  { name: "Coop. Aho. y Cred. Nueva Huancavilca", code: "408" },
  { name: "Coop. Aho. y Cred. Nueva Jerusalen", code: "272" },
  { name: "Coop. Aho. y Cred. Nuevos Horizontes El Oro Ltda.", code: "659" },
  { name: "Coop. Aho. y Cred. Once de Junio", code: "075" },
  { name: "Coop. Aho. y Cred. Oscus", code: "076" },
  { name: "Coop. Aho. y Cred. Pablo Munoz Vega", code: "093" },
  { name: "Coop. Aho. y Cred. Padre Julian Lorente Ltda", code: "077" },
  { name: "Coop. Aho. y Cred. Pedro Moncayo Ltda.", code: "279" },
  { name: "Coop. Aho. y Cred. Peq Emp Cacpe Yanzatza", code: "404" },
  { name: "Coop. Aho. y Cred. Peq Empr Cacpe Biblian", code: "078" },
  { name: "Coop. Aho. y Cred. Peq Empresa Gualaquiza", code: "402" },
  { name: "Coop. Aho. y Cred. Peq. Emp. de Loja Cacpe", code: "350" },
  { name: "Coop. Aho. y Cred. Pijal", code: "640" },
  { name: "Coop. Aho. y Cred. Pilahuin", code: "643" },
  { name: "Coop. Aho. y Cred. Pilahuin Tio Ltda", code: "608" },
  { name: "Coop. Aho. y Cred. Profesionales del Volante Union L", code: "655" },
  { name: "Coop. Aho. y Cred. Progreso", code: "079" },
  { name: "Coop. Aho. y Cred. Provida", code: "281" },
  { name: "Coop. Aho. y Cred. Pucara Ltda.", code: "644" },
  { name: "Coop. Aho. y Cred. Puellaro Ltda", code: "271" },
  { name: "Coop. Aho. y Cred. Puerto Lopez Ltda", code: "425" },
  { name: "Coop. Aho. y Cred. Quilanga Ltda.", code: "651" },
  { name: "Coop. Aho. y Cred. Riobamba", code: "080" },
  { name: "Coop. Aho. y Cred. Salasaca", code: "637" },
  { name: "Coop. Aho. y Cred. San Antonio Ltda.", code: "289" },
  { name: "Coop. Aho. y Cred. San Francisco", code: "081" },
  { name: "Coop. Aho. y Cred. San Francisco de Asis", code: "054" },
  { name: "Coop. Aho. y Cred. San Gabriel Ltda.", code: "328" },
  { name: "Coop. Aho. y Cred. San Jorge Ltda", code: "428" },
  { name: "Coop. Aho. y Cred. San Jose Ltda", code: "082" },
  { name: "Coop. Aho. y Cred. San Jose S.J.", code: "283" },
  { name: "Coop. Aho. y Cred. San Miguel de Los Bancos", code: "330" },
  { name: "Coop. Aho. y Cred. San Miguel de Sigchos", code: "646" },
  { name: "Coop. Aho. y Cred. Santa Ana Ltda", code: "084" },
  { name: "Coop. Aho. y Cred. Santa Anita Ltda", code: "418" },
  { name: "Coop. Aho. y Cred. Santa Rosa de Patutan Ltda.", code: "334" },
  { name: "Coop. Aho. y Cred. Santa Rosa Ltda", code: "096" },
  { name: "Coop. Aho. y Cred. Semilla del Progreso Ltda", code: "332" },
  { name: "Coop. Aho. y Cred. Senor de Giron", code: "285" },
  { name: "Coop. Aho. y Cred. Sierra Centro Ltda.", code: "647" },
  { name: "Coop. Aho. y Cred. Simiatug Ltda", code: "639" },
  { name: "Coop. Aho. y Cred. Sinchi Runa Ltda", code: "645" },
  { name: "Coop. Aho. y Cred. Sumac Llacta Ltda.", code: "662" },
  { name: "Coop. Aho. y Cred. Tena Ltda.", code: "276" },
  { name: "Coop. Aho. y Cred. Tulcan", code: "222" },
  { name: "Coop. Aho. y Cred. Tungurahua Ltda.", code: "287" },
  { name: "Coop. Aho. y Cred. Union Mercedaria Ltda.", code: "648" },
  { name: "Coop. Aho. y Cred. Valles del Lirio", code: "632" },
  { name: "Coop. Aho. y Cred. Vencedores de Tungurahua", code: "629" },
  { name: "Coop. Calceta Ltda", code: "087" },
  { name: "Coop. Capeco Ltda", code: "203" },
  { name: "Coop. Esfuerzo Unido Para El Desarr. del Chilco La", code: "633" },
  { name: "Coop. Jardin Azuayo", code: "015" },
  { name: "Coop. Juventud Ecuatoriana Progresista Ltda.", code: "091" },
  { name: "Coop. Manuel Esteban Godoy Ortega Ltda Coopmego", code: "092" },
  { name: "Coop. Peq. Empresa de Pastaza", code: "089" },
  { name: "Coop. Policia Nacional", code: "053" },
  { name: "Coop. Prevision Ahorro y Desarrollo", code: "094" },
  { name: "COOP DE A. Y C. 22 de Junio-Orianga", code: "119" },
  { name: "COOP DE A. Y C. Mushuk Yuyay Ltda", code: "102" },
  { name: "COOP DE A. Y C. Nizag Ltda.", code: "103" },
  { name: "COOP DE A. Y C. Quilotoa", code: "118" },
  { name: "COOP DE A. Y C. Sembrando Futuro", code: "179" },
  { name: "COOP DE A. Y C. Senor Del Arbol", code: "114" },
  { name: "COOP DE A. Y C. Unidad Y Progreso", code: "100" },
  { name: "COOP.DE Ahorro Y Credito 29 de Enero", code: "108" },
  { name: "COOP.DE Ahorro Y Credito Ciudad de Zamora", code: "182" },
  { name: "Cooperativa de Ahorro y Credito Ambato Ltda.", code: "122" },
  { name: "Cooperativa de Ahorro y Credito Armada Nacional", code: "194" },
  { name: "Cooperativa de Ahorro y Credito Campesina Coopac", code: "125" },
  { name: "Cooperativa de Ahorro y Credito Distrito Metropol", code: "196" },
  { name: "Cooperativa de Ahorro y Credito General Angel Flor", code: "200" },
  { name: "Cooperativa de Ahorro y Credito Santa Isabel Ltda", code: "176" },
  { name: "Cooperativa Divino Nino", code: "177" },
  { name: "Cooperativa Llacta Pura", code: "178" },
  { name: "COPP Aho Cred Credisur", code: "668" },
  { name: "COOP.AHO Y Cred Camara de Comercio Pindal Cadecopi", code: "649" },
  { name: "COOP Aho Y Cred 20 de Febrero Ltda", code: "674" },
  { name: "COOP Aho Y Cred Caseg Ltda", code: "671" },
  { name: "COOP Aho Y Cred Finan Indigena", code: "673" },
  { name: "COOP Aho Y Cred Focla", code: "672" },
  { name: "COOP Aho Y Cred Gral Ruminahui", code: "670" },
  { name: "COOP Aho Y Cred Huaquillas", code: "677" },
  { name: "COOP Aho Y Cred Indigena Alfa", code: "675" },
  { name: "COOP Aho Y Cred Maquita Cushunchic", code: "669" },
  { name: "Financiera - Diners Club del Ecuador", code: "232" },
  { name: "Financiera Acceso La Paz", code: "43" },
  { name: "Financiera Financoop", code: "097" },
  { name: "Fondo Financiero de la Comunidad", code: "44" },
  { name: "FONDO DE CESANTIA DEL MAGISTERIO ECUATORIANO FCME-", code: "667" },
  { name: "Interdin S.A.", code: "349" },
  { name: "La Cooperativa de Ah Y Cred Simon Bolivar", code: "198" },
  { name: "Magisterio Rural", code: "39" },
  { name: "Mutualista Ambato", code: "098" },
  { name: "Mutualista Azuay", code: "070" },
  { name: "Mutualista Imbabura", code: "099" },
  { name: "Mutualista Pichincha", code: "071" },
  { name: "Nacional Financiera Boliviana SAN", code: "42" },
  { name: "Pacificard", code: "005" }
];

/** México — dLocal Go Country requirements. */
const MX_BANK_CODES: DlocalBankCode[] = [
  { name: "ABC Capital", code: "138" },
  { name: "Actinver", code: "133" },
  { name: "Afirme", code: "62" },
  { name: "Albo", code: "721" },
  { name: "Arcus", code: "706" },
  { name: "Autofin", code: "128" },
  { name: "Azteca", code: "127" },
  { name: "BaBien", code: "166" },
  { name: "Bajio", code: "30" },
  { name: "Banamex", code: "2" },
  { name: "Bancomext", code: "6" },
  { name: "Bancoppel", code: "137" },
  { name: "Banjercito", code: "19" },
  { name: "Banobras", code: "9" },
  { name: "Banorte", code: "72" },
  { name: "Banregio", code: "58" },
  { name: "Bansi", code: "60" },
  { name: "BANXICO", code: "1" },
  { name: "Barclays", code: "129" },
  { name: "Bbase", code: "145" },
  { name: "BBVA Bancomer", code: "12" },
  { name: "BMonex", code: "112" },
  { name: "BMultiva", code: "132" },
  { name: "Banco Covalto", code: "154" },
  { name: "Banco S3", code: "160" },
  { name: "Banco Sabadell", code: "156" },
  { name: "Bancrea", code: "152" },
  { name: "Bank of America", code: "106" },
  { name: "Bank of China", code: "159" },
  { name: "Bankaool", code: "147" },
  { name: "Caja Pop Mexicana", code: "677" },
  { name: "Caja Telefonistas", code: "683" },
  { name: "Cartera Digital", code: "715" },
  { name: "Citi", code: "124" },
  { name: "CLS", code: "901" },
  { name: "CoDi Valida", code: "903" },
  { name: "Compartamos", code: "130" },
  { name: "Consubanco", code: "140" },
  { name: "Credicapital", code: "652" },
  { name: "Crediclub", code: "688" },
  { name: "Cristobal Colon", code: "680" },
  { name: "Cuenca", code: "723" },
  { name: "Donde", code: "151" },
  { name: "Finamex", code: "616" },
  { name: "Fincomun", code: "634" },
  { name: "FOMPED", code: "689" },
  { name: "Fondeadora", code: "699" },
  { name: "Fondo (FIRA)", code: "685" },
  { name: "GBM", code: "601" },
  { name: "Hey Banco", code: "167" },
  { name: "Hipotecaria Federal", code: "168" },
  { name: "HSBC", code: "21" },
  { name: "ICBC", code: "155" },
  { name: "Inbursa", code: "36" },
  { name: "Indeval", code: "902" },
  { name: "Inmobiliario", code: "150" },
  { name: "Invex", code: "59" },
  { name: "JP Morgan", code: "110" },
  { name: "Klar", code: "661" },
  { name: "Kuspit", code: "653" },
  { name: "Libertad", code: "670" },
  { name: "Masari", code: "602" },
  { name: "Mercado Pago", code: "722" },
  { name: "MexPago", code: "720" },
  { name: "Mifel", code: "42" },
  { name: "Mizuho Bank", code: "158" },
  { name: "Monexcb", code: "600" },
  { name: "MUFG", code: "108" },
  { name: "Nafin", code: "135" },
  { name: "Nu Bank", code: "638" },
  { name: "NVIO", code: "710" },
  { name: "Opciones Empresariales del Noroeste", code: "659" },
  { name: "Pagatodo", code: "148" },
  { name: "Peibo", code: "732" },
  { name: "Profuturo", code: "620" },
  { name: "Santander", code: "14" },
  { name: "Scotiabank", code: "44" },
  { name: "Shinhan", code: "157" },
  { name: "SPIN BY OXXO", code: "728" },
  { name: "STP", code: "646" },
  { name: "Tesored", code: "703" },
  { name: "Transfer", code: "684" },
  { name: "Unagra", code: "656" },
  { name: "Valmex", code: "617" },
  { name: "Value", code: "605" },
  { name: "Ve Por Mas", code: "113" },
  { name: "Vector", code: "608" },
  { name: "Volkswagen", code: "141" }
];

/** Perú — dLocal Go Country requirements. */
const PE_BANK_CODES: DlocalBankCode[] = [
  { name: "Banco Central de Reserva", code: "001" },
  { name: "Banco de Comercio", code: "023" },
  { name: "Banco de Crédito del Perú", code: "002" },
  { name: "Banco de la Nación", code: "018" },
  { name: "Banco del Pichincha", code: "010" },
  { name: "Banco Falabella", code: "054" },
  { name: "Banco Financiero", code: "035" },
  { name: "Banco GNB Perú S.A.", code: "053" },
  { name: "Banco Interamericano de Finanzas (BIF)", code: "038" },
  { name: "Banco Ripley", code: "055" },
  { name: "BBVA Continental", code: "011" },
  { name: "Caja Metropolitana de Lima", code: "800" },
  { name: "Caja Municipal de Ahorro y Crédito Arequipa", code: "803" },
  { name: "Caja Municipal de Ahorro y Crédito Cuzco", code: "806" },
  { name: "Caja Municipal de Ahorro y Crédito Huancayo", code: "808" },
  { name: "Caja Municipal de Ahorro y Crédito Piura SAC", code: "801" },
  { name: "Caja Municipal de Ahorro y Crédito Tacna", code: "813" },
  { name: "Citibank", code: "007" },
  { name: "Crediscotia Financiera", code: "043" },
  { name: "Interbank", code: "003" },
  { name: "Mi Banco", code: "049" },
  { name: "Santander", code: "056" },
  { name: "Scotiabank", code: "009" },
  { name: "Yape", code: "037" },
  { name: "Plin", code: "040" },
  { name: "Tarjetas Peruanas Prepago", code: "043" },
  { name: "Prex", code: "045" },
  { name: "Dale", code: "048" }
];

/** Paraguay — dLocal Go Country requirements. */
const PY_BANK_CODES: DlocalBankCode[] = [
  { name: "Banco Amambay S.A.", code: "1" },
  { name: "Banco Atlas S.A.", code: "2" },
  { name: "Banco BASA S.A.", code: "3" },
  { name: "Banco Busaif S.A. de Inversion y Fomento", code: "5" },
  { name: "Banco Central del Paraguay", code: "6" },
  { name: "Banco Comercial Paraguayo S.A.", code: "7" },
  { name: "Banco Continental S.A.E.C.A.", code: "8" },
  { name: "Banco Corporacion S.A.", code: "9" },
  { name: "Banco de Desarrollo del Paraguay S.A.", code: "10" },
  { name: "Banco de Inversiones del Paraguay", code: "11" },
  { name: "Banco de La Nacion Argentina", code: "12" },
  { name: "Banco Do Brasil S.A.", code: "13" },
  { name: "Banco Familiar S.A.E.C.A.", code: "14" },
  { name: "Banco General S.A.", code: "16" },
  { name: "Banco GNB Paraguay S.A.", code: "17" },
  { name: "Banco Itapua S.A.E.C.A.", code: "18" },
  { name: "Banco Itau Paraguay S.A.", code: "19" },
  { name: "Banco Nacional de Fomento", code: "20" },
  { name: "Banco Nacional de Trabajadores", code: "21" },
  { name: "Banco Para la Comercializacion Y La Produccion S.A (BANCOP S.A.)", code: "22" },
  { name: "Banco Paraguayo Oriental de Inversion y Fomento S.A.", code: "23" },
  { name: "Banco Regional S.A.E.C.A.", code: "24" },
  { name: "Banco Rio S.A.E.C.A.", code: "25" },
  { name: "BOLPAR Sociedad Anonima", code: "26" },
  { name: "British American Tobacco Productora de Cigarrillos S.A.", code: "28" },
  { name: "Citibank N.A.", code: "29" },
  { name: "Crisol y Encarnacion Financiera S.A.", code: "30" },
  { name: "Financiera Exportadora Paraguaya S.A.", code: "32" },
  { name: "Financiera Paraguayo Japonesa S.A.E.C.A.", code: "33" },
  { name: "Finlantina S.A. de Finanzas", code: "40" },
  { name: "Fonplata - Fondo Financiero Para El Desarollo de La Cuenca Del Plata", code: "34" },
  { name: "GNB Fusion", code: "4" },
  { name: "Grupo Internacional de Finanzas S.A. C.A. (Interfisa Financiera)", code: "35" },
  { name: "Sudameris Bank S.A.E.C.A.", code: "37" },
  { name: "Summa Asesories", code: "38" },
  { name: "Tu Financiera", code: "42" },
  { name: "Ueno Bank S.A.", code: "48" }
];

/** Uruguay — dLocal Go Country requirements. */
const UY_BANK_CODES: DlocalBankCode[] = [
  { name: "Banco Bilbao Vizcaya Argentaria", code: "153" },
  { name: "Banco de la Nación Argentina", code: "246" },
  { name: "Banco Hipotecario del Uruguay", code: "091" },
  { name: "Banco ITAU", code: "113" },
  { name: "Banco Santander", code: "137" },
  { name: "Banque Heritage", code: "162" },
  { name: "Bapro", code: "61" },
  { name: "BROU - Banco de la República Oriental del Uruguay", code: "001" },
  { name: "Citibank N.A. Sucursal", code: "205" },
  { name: "HSBC Bank", code: "157" },
  { name: "Mi Dinero", code: "917" },
  { name: "Oca Blue", code: "999" },
  { name: "Prex", code: "603" },
  { name: "Redpagos", code: "624" },
  { name: "Scotiabank", code: "128" }
];

/** Todas las listas oficiales por país habilitado para payouts en dLocal Go. */
export const DLOCAL_PAYOUT_BANK_CODES: Record<DlocalPayoutCountry, DlocalBankCode[]> = {
  AR: AR_BANK_CODES,
  BR: BR_BANK_CODES,
  EC: EC_BANK_CODES,
  MX: MX_BANK_CODES,
  PE: PE_BANK_CODES,
  PY: PY_BANK_CODES,
  UY: UY_BANK_CODES
};

/** Devuelve la lista de bancos de un país (siempre disponible para países habilitados). */
export function dlocalPayoutBankCodes(country: DlocalPayoutCountry): DlocalBankCode[] | null {
  return DLOCAL_PAYOUT_BANK_CODES[country] ?? null;
}

/** ¿El país usa selector de banco (lista oficial cargada) o entrada manual del `bank_code`? */
export function dlocalPayoutBankCodeMode(country: DlocalPayoutCountry): "list" | "manual" {
  return DLOCAL_PAYOUT_BANK_CODES[country] && DLOCAL_PAYOUT_BANK_CODES[country].length > 0 ? "list" : "manual";
}

/** Verifica que un `bank_code` pertenezca a la lista oficial del país. */
export function isKnownDlocalBankCode(country: DlocalPayoutCountry, code: string | null | undefined): boolean {
  const list = DLOCAL_PAYOUT_BANK_CODES[country];
  if (!list) {
    return false;
  }
  const normalized = (code ?? "").trim();
  return list.some((bank) => bank.code === normalized);
}
