/** Países de Latinoamérica y el Caribe (habitual en onboarding). Valor = etiqueta en español. */
export const LATIN_AMERICA_COUNTRY_OPTIONS: { value: string; label: string }[] = [
  { value: "Antigua y Barbuda", label: "Antigua y Barbuda" },
  { value: "Argentina", label: "Argentina" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belice", label: "Belice" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Brasil", label: "Brasil" },
  { value: "Chile", label: "Chile" },
  { value: "Colombia", label: "Colombia" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Dominica", label: "Dominica" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Granada", label: "Granada" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guyana", label: "Guyana" },
  { value: "Haití", label: "Haití" },
  { value: "Honduras", label: "Honduras" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "México", label: "México" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Panamá", label: "Panamá" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Perú", label: "Perú" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "República Dominicana", label: "República Dominicana" },
  { value: "San Cristóbal y Nieves", label: "San Cristóbal y Nieves" },
  { value: "Santa Lucía", label: "Santa Lucía" },
  { value: "San Vicente y las Granadinas", label: "San Vicente y las Granadinas" },
  { value: "Surinam", label: "Surinam" },
  { value: "Trinidad y Tobago", label: "Trinidad y Tobago" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" }
].sort((a, b) => a.label.localeCompare(b.label, "es"));

/**
 * Áreas de atención (onboarding web y edición de perfil). Valores canónicos en español.
 * Alineado con motivos de consulta del paciente hasta "Crecimiento personal", con LGBTIQ+ y Psicosomáticos.
 */
export const ATTENTION_AREA_OPTIONS_ES: string[] = [
  "Ansiedad",
  "Autoestima",
  "Pareja",
  "Duelo",
  "Depresión",
  "Adicciones",
  "Trauma",
  "Infancia y adolescencia",
  "Estrés laboral",
  "LGBTIQ+",
  "Alimentación",
  "Dolor crónico",
  "TOC",
  "Mindfulness",
  "Ataques de pánico",
  "Estrés",
  "Problemas de autoestima",
  "Dificultad en relaciones",
  "Rupturas amorosas o duelos",
  "Problemas laborales o burnout",
  "Toma de decisiones importantes",
  "Falta de motivación o propósito",
  "Problemas de sueño",
  "Manejo de emociones",
  "Consumo o conductas adictivas",
  "Experiencias difíciles del pasado",
  "Crisis personales",
  "Soledad",
  "Dificultad para controlar impulsos",
  "Crecimiento personal",
  "Psicosomáticos"
];
